### ISSUE TITLE
Roadmap for project

### ISSUE THREAD

**Issue by sumanthvrao** [pes-innovation-lab/web#1]
- [x]  Learn about Mlab (About page) - what is it. When did it start? Whose faculty in-charge? How can I be a part of it? What programs does it conduct?

- [ ]  See updates/ news of recent events 'Breaking news style'

- [x]  Achievements of previous and current Mlab folks. Name - when they interned - a little bit about their project -achievements of the project

- [x] Projects conducted. Sorted chronologically. 2019,18,17...... Till we have data on projects.

- [x] An easy enough UI to navigate across all this.

**Comment by sumanthvrao** [comment]
@souravtecken FYI

**Comment by DarkAEther** [comment]
> Achievements of previous and current Mlab folks. Name - when they interned - a little bit about their project -achievements of the project

We decided to stick with publications for the time being.

- [x] Publications page for papers
